# Generated by Django 2.0 on 2017-12-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20171209_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='defaultName', max_length=40, verbose_name='Имя файла'),
        ),
    ]
