# Generated by Django 2.0 on 2017-12-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='datetime_create',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Время загрузки файла'),
        ),
    ]
