djangoquizz:
  build: ./..
  volumes:
    - ./..:/opt/django
  links:
   - m3208helper_db
  ports:
   - "0.0.0.0:5555:8080"
  environment:
   - DATABASE=postgres://postgres@m3208helper_db/m3208helper_db
dbquizz:
  image: postgres:9.4
  ports:
   - "0.0.0.0:5433:5433"
  volumes: 
   - ./pgsql:/var/lib/postgresql/data


