# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='child_folders',
        ),
        migrations.AddField(
            model_name='folder',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='file_system.Folder'),
        ),
    ]
