# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0003_auto_20171002_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_creation',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='date_creation',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
