# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0005_auto_20171007_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название файла'),
        ),
    ]
